# Generated by Django 3.2.8 on 2021-10-21 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sekil', models.ImageField(upload_to='images/')),
                ('info', models.CharField(max_length=255)),
            ],
        ),
    ]
